version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      day: saturday
      interval: weekly
  # app
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
    groups:
      minor & patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  # website
  - package-ecosystem: npm
    directory: /website
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      minor & patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
