version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      day: saturday
      interval: weekly

  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
